### ISSUE TITLE
Building on Mac OS X

### ISSUE THREAD

**Issue by ghost91-** [teeworlds/teeworlds#1005]
When trying to build the client on Mac OS X 10.7 with XCode 4, I get the following error:

```
[80/96] #1 c++ src/engine/client/backend_sdl.cpp
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:161,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:21,
                 from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:20,
                 from /System/Library/Frameworks/AGL.framework/Headers/agl.h:21,
                 from src/engine/client/backend_sdl.h:31,
                 from src/engine/client/backend_sdl.cpp:8:
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/fp.h:1197: error: conflicting declaration ‘const double_t pi’
src/base/math.h:64: error: ‘pi’ has a previous declaration as ‘const float pi
```

The content of line 1197 in /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/fp.h is this:

```
extern const double_t pi                                             AVAILABLE_MAC_OS_X_VERSION_10_0_AND_LATER;
```

It seems that building on other systems running Mac OS X is also broken, MAP94 gets this when trying to compile on 10.5.8 (intel) with xcode 3:

```

src/game/client/components/menus.cpp: In member function ‘void CMenus::UiDoListboxStart(const void*, float, const char*, int, int, int, float, const CUIRect*)’:
src/game/client/components/menus.cpp:751: warning: unused variable ‘Header’
src/game/client/components/menus.cpp: In member function ‘int CMenus::Render()’:
src/game/client/components/menus.cpp:1525: warning: unused variable ‘BottomView’
src/game/client/components/menus_settings.cpp: In member function ‘void CMenus::RenderSettingsTeeCustom(CUIRect)’:
src/game/client/components/menus_settings.cpp:877: warning: unused variable ‘Button’
src/game/client/components/menus_settings.cpp: In member function ‘void CMenus::RenderSettingsGraphics(CUIRect)’:
src/game/client/components/menus_settings.cpp:1358: warning: unused variable ‘G’
src/base/tl/threading.h: In function ‘unsigned int atomic_inc(volatile unsigned int*)’:
src/base/tl/threading.h:17: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_dec(volatile unsigned int*)’:
src/base/tl/threading.h:22: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_compswap(volatile unsigned int*, unsigned int, unsigned int)’:
src/base/tl/threading.h:27: error: ‘__sync_val_compare_and_swap’ was not declared in this scope
src/base/tl/threading.h: In function ‘void sync_barrier()’:
src/base/tl/threading.h:32: error: ‘__sync_synchronize’ was not declared in this scope
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/fp.h: At global scope:
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/fp.h:1198: error: conflicting declaration ‘const double_t pi’
src/base/math.h:64: error: ‘pi’ has a previous declaration as ‘const float pi’
src/base/tl/threading.h: In function ‘unsigned int atomic_inc(volatile unsigned int*)’:
src/base/tl/threading.h:17: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_dec(volatile unsigned int*)’:
src/base/tl/threading.h:22: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_compswap(volatile unsigned int*, unsigned int, unsigned int)’:
src/base/tl/threading.h:27: error: ‘__sync_val_compare_and_swap’ was not declared in this scope
src/base/tl/threading.h: In function ‘void sync_barrier()’:
src/base/tl/threading.h:32: error: ‘__sync_synchronize’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_inc(volatile unsigned int*)’:
src/base/tl/threading.h:17: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_dec(volatile unsigned int*)’:
src/base/tl/threading.h:22: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_compswap(volatile unsigned int*, unsigned int, unsigned int)’:
src/base/tl/threading.h:27: error: ‘__sync_val_compare_and_swap’ was not declared in this scope
src/base/tl/threading.h: In function ‘void sync_barrier()’:
src/base/tl/threading.h:32: error: ‘__sync_synchronize’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_inc(volatile unsigned int*)’:
src/base/tl/threading.h:17: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_dec(volatile unsigned int*)’:
src/base/tl/threading.h:22: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_compswap(volatile unsigned int*, unsigned int, unsigned int)’:
src/base/tl/threading.h:27: error: ‘__sync_val_compare_and_swap’ was not declared in this scope
src/base/tl/threading.h: In function ‘void sync_barrier()’:
src/base/tl/threading.h:32: error: ‘__sync_synchronize’ was not declared in this scope
src/game/client/components/menus.cpp: In member function ‘void CMenus::UiDoListboxStart(const void*, float, const char*, int, int, int, float, const CUIRect*)’:
src/game/client/components/menus.cpp:751: warning: unused variable ‘Header’
src/game/client/components/menus.cpp: In member function ‘int CMenus::Render()’:
src/game/client/components/menus.cpp:1525: warning: unused variable ‘BottomView’
src/game/client/components/menus_settings.cpp: In member function ‘void CMenus::RenderSettingsTeeCustom(CUIRect)’:
src/game/client/components/menus_settings.cpp:877: warning: unused variable ‘Button’
src/game/client/components/menus_settings.cpp: In member function ‘void CMenus::RenderSettingsGraphics(CUIRect)’:
src/game/client/components/menus_settings.cpp:1358: warning: unused variable ‘G’
src/base/tl/threading.h: In function ‘unsigned int atomic_inc(volatile unsigned int*)’:
src/base/tl/threading.h:17: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_dec(volatile unsigned int*)’:
src/base/tl/threading.h:22: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_compswap(volatile unsigned int*, unsigned int, unsigned int)’:
src/base/tl/threading.h:27: error: ‘__sync_val_compare_and_swap’ was not declared in this scope
src/base/tl/threading.h: In function ‘void sync_barrier()’:
src/base/tl/threading.h:32: error: ‘__sync_synchronize’ was not declared in this scope
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/fp.h: At global scope:
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/fp.h:1198: error: conflicting declaration ‘const double_t pi’
src/base/math.h:64: error: ‘pi’ has a previous declaration as ‘const float pi’
src/base/tl/threading.h: In function ‘unsigned int atomic_inc(volatile unsigned int*)’:
src/base/tl/threading.h:17: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_dec(volatile unsigned int*)’:
src/base/tl/threading.h:22: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_compswap(volatile unsigned int*, unsigned int, unsigned int)’:
src/base/tl/threading.h:27: error: ‘__sync_val_compare_and_swap’ was not declared in this scope
src/base/tl/threading.h: In function ‘void sync_barrier()’:
src/base/tl/threading.h:32: error: ‘__sync_synchronize’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_inc(volatile unsigned int*)’:
src/base/tl/threading.h:17: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_dec(volatile unsigned int*)’:
src/base/tl/threading.h:22: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_compswap(volatile unsigned int*, unsigned int, unsigned int)’:
src/base/tl/threading.h:27: error: ‘__sync_val_compare_and_swap’ was not declared in this scope
src/base/tl/threading.h: In function ‘void sync_barrier()’:
src/base/tl/threading.h:32: error: ‘__sync_synchronize’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_inc(volatile unsigned int*)’:
src/base/tl/threading.h:17: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_dec(volatile unsigned int*)’:
src/base/tl/threading.h:22: error: ‘__sync_fetch_and_add’ was not declared in this scope
src/base/tl/threading.h: In function ‘unsigned int atomic_compswap(volatile unsigned int*, unsigned int, unsigned int)’:
src/base/tl/threading.h:27: error: ‘__sync_val_compare_and_swap’ was not declared in this scope
src/base/tl/threading.h: In function ‘void sync_barrier()’:
src/base/tl/threading.h:32: error: ‘__sync_synchronize’ was not declared in this scope
```
