### ISSUE TITLE
does not compile with GCC 6.0

### ISSUE THREAD

**Issue by ignatenkobrain** [teeworlds/teeworlds#1456]
https://bugzilla.redhat.com/attachment.cgi?id=1126599

```
src/mastersrv/mastersrv.cpp:120:106: error: narrowing conversion of '255' from 'int' to 'char' inside { } [-Wnarrowing]
     static char IPV4Mapping[] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF };
                                                                                                          ^
```

```
In file included from /usr/include/c++/6.0.0/math.h:36:0,
                 from src/game/gamecore.h:9,
                 from src/game/gamecore.cpp:3:
/usr/include/c++/6.0.0/cmath: In function 'constexpr float std::round(float)':
/usr/include/c++/6.0.0/cmath:1708:18: error: 'constexpr float std::round(float)' conflicts with a previous declaration
   round(float __x)
                  ^
In file included from src/game/gamecore.h:7:0,
                 from src/game/gamecore.cpp:3:
src/base/math.h:23:12: note: previous declaration 'int round(float)'
 inline int round(float f)
            ^~~~~
In file included from src/game/gamecore.h:9:0,
                 from src/game/gamecore.cpp:3:
/usr/include/c++/6.0.0/math.h: At global scope:
/usr/include/c++/6.0.0/math.h:107:12: error: 'constexpr float std::round(float)' conflicts with a previous declaration
 using std::round;
            ^~~~~
In file included from src/game/gamecore.h:7:0,
                 from src/game/gamecore.cpp:3:
src/base/math.h:23:12: note: previous declaration 'int round(float)'
 inline int round(float f)
            ^~~~~
```

**Comment by heinrich5991** [comment]
Fixed in commit https://github.com/teeworlds/teeworlds/commit/bdd4b8c2b0ce4be986cb51a1dbc5d05db9a76867, but there hasn't been any release with it yet.

**Comment by ignatenkobrain** [comment]
this part fixed, but not second:
```
src/mastersrv/mastersrv.cpp: In function 'void BuildPackets()':
src/mastersrv/mastersrv.cpp:120:106: error: narrowing conversion of '255' from 'int' to 'char' inside { } [-Wnarrowing]
     static char IPV4Mapping[] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF };
                                                                                                          ^
src/mastersrv/mastersrv.cpp:120:106: error: narrowing conversion of '255' from 'int' to 'char' inside { } [-Wnarrowing]
```

**Comment by heinrich5991** [comment]
Oh sorry, didn't notice that these turned into errors.

**Comment by oy** [comment]
Fixed.
