### PR TITLE
Replace nullptr by NULL, fixing compilation errors; also, correct the warning fix

### PR DESCRIPTION
**Pull request by Dune-jr**
Compilation is broken since 5ef5a2655c09b91ba49946862f7bedbe9c84d9bc.
Should use NULL instead of `nullptr`:

https://github.com/teeworlds/teeworlds/blob/5ef5a2655c09b91ba49946862f7bedbe9c84d9bc/src/game/client/components/menus_settings.cpp#L1186-L1187

### CODE REVIEW

**Comment by Dune-jr** [comment]
Also fixed some warnings introduced by fd142e054ba489ecd59b0cfa8c1791149ffb5bce that were wrongly fixed by 6bea95dbfa2955fce9ab8d85ba32e976e785bfd1, introducing a bug.

File: src/game/client/components/menus_settings.cpp [hunk 1]
```diff
@@ -1183,7 +1183,7 @@ bool CMenus::DoResolutionList(CUIRect* pRect, CListBoxState* pListBoxState,
 	int OldSelected = -1;
 	char aBuf[32];
 
-	UiDoListboxStart(pListBoxState, pListBoxState, 20.0f, nullptr, lModes.size(), 1,
+	UiDoListboxStart(pListBoxState, pListBoxState, 20.0f, NULL, lModes.size(), 1,
```
Comment (oy) [inline src/game/client/components/menus_settings.cpp]: Could you change it to 0 for consistency?

File: src/game/client/components/chat.cpp [hunk 2]
```diff
@@ -430,7 +430,7 @@ void CChat::AddLine(int ClientID, int Mode, const char *pLine)
 			{
 				int Length = str_length(m_pClient->m_aClients[m_pClient->m_LocalClientID].m_aName);
 				if((pLine == pHL || pHL[-1] == ' ') // space or nothing before
-					&& (((pHL[Length] == 0 || pHL[Length] == ' ') || pHL[Length] == ':') && (pHL[Length+1] == 0 || pHL[Length+1] == ' '))) // space or nothing after, allowing a colon
+					&& ((pHL[Length] == 0 || pHL[Length] == ' ') || (pHL[Length] == ':' && (pHL[Length+1] == 0) || pHL[Length+1] == ' '))) // space or nothing after, allowing a colon
```
Comment (oy) [inline src/game/client/components/chat.cpp]: Should be
`&& ((pHL[Length] == 0 || pHL[Length] == ' ') || (pHL[Length] == ':' && (pHL[Length+1] == 0 || pHL[Length+1] == ' ')))) // space or nothing after, allowing a colon` 
right? Otherwise pHL[Length] could be anything as long as pHL[Length+1] is ' '.

Comment (Dune-jr) [reply src/game/client/components/chat.cpp]: Dammit, you are right. Makes me think this kind of complex logical expressions should be split in several `if`.

Comment (oy) [reply src/game/client/components/chat.cpp]: Yeah, probably better.
